version: '3.10'

services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres_db
    volumes:
      - .:/app

volumes:
  postgres_data:
