"""Initial migrations

Revision ID: 0fa65480a142
Revises: 
Create Date: 2024-04-28 11:59:40.622222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa65480a142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_auth_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cart_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'auth_user', ['auth_user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('cart_item_shoppig_cart_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cart_item_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cart', ['shoppig_cart_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('invoice_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart', sa.Integer(), nullable=True))
        batch_op.drop_constraint('order_order_status_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('order_address_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('order_delivery_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_status', ['order_status_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'cart', ['cart'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'delivery', ['delivery_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'address', ['address_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('size_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_type_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['stock_number'])
        batch_op.create_foreign_key(None, 'size', ['size_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'product_type', ['product_type_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('product_monthly_reports', schema=None) as batch_op:
        batch_op.drop_constraint('product_monthly_reports_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.drop_constraint('product_type_size_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'size_type', ['size_type_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.drop_constraint('size_size_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'size_type', ['size_type_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('size', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('size_size_type_id_fkey', 'size_type', ['size_type_id'], ['id'])

    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_type_size_type_id_fkey', 'size_type', ['size_type_id'], ['id'])

    with op.batch_alter_table('product_monthly_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_monthly_reports_product_id_fkey', 'product', ['product_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('product_type_id')
        batch_op.drop_column('size_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('stock_number')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_delivery_id_fkey', 'delivery', ['delivery_id'], ['id'])
        batch_op.create_foreign_key('order_address_id_fkey', 'address', ['address_id'], ['id'])
        batch_op.create_foreign_key('order_order_status_id_fkey', 'order_status', ['order_status_id'], ['id'])
        batch_op.drop_column('cart')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invoice_order_id_fkey', 'order', ['order_id'], ['id'])

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_item_product_id_fkey', 'product', ['product_id'], ['id'])
        batch_op.create_foreign_key('cart_item_shoppig_cart_id_fkey', 'cart', ['shoppig_cart_id'], ['id'])

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_order_id_fkey', 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key('cart_auth_user_id_fkey', 'auth_user', ['auth_user_id'], ['id'])

    # ### end Alembic commands ###
