"""add product_category, rename product_item and delivery_method

Revision ID: 2e04442f870a
Revises: 75bce4a1825b
Create Date: 2024-05-15 17:01:44.551951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e04442f870a'
down_revision = '75bce4a1825b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_item_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('cart_item_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_item', ['product_item_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_method_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('order_delivery_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'delivery_method', ['delivery_method_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('delivery_id')

    with op.batch_alter_table('product_monthly_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_item_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('product_monthly_reports_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_item', ['product_item_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_category_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('product_type_size_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_category', ['product_category_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('size_type_id')
    op.drop_table('delivery')
    op.drop_table('product')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_type_size_type_id_fkey', 'size_type', ['size_type_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('product_category_id')

    with op.batch_alter_table('product_monthly_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_monthly_reports_product_id_fkey', 'product', ['product_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('product_item_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_delivery_id_fkey', 'delivery', ['delivery_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('delivery_method_id')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_item_product_id_fkey', 'product', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('product_item_id')

    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('stock_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], name='product_product_type_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], name='product_size_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_pkey'),
    sa.UniqueConstraint('name', name='product_name_key'),
    sa.UniqueConstraint('stock_number', name='product_stock_number_key')
    )
    op.create_table('delivery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='delivery_pkey'),
    sa.UniqueConstraint('name', name='delivery_name_key'),
    sa.UniqueConstraint('price', name='delivery_price_key')
    )
    # ### end Alembic commands ###
