"""CartItem.shoppig_cart_id changed to CartItem.shopping_cart_id

Revision ID: 75bce4a1825b
Revises: a32c06e79f74
Create Date: 2024-04-28 17:01:20.126524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bce4a1825b'
down_revision = 'a32c06e79f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopping_cart_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('cart_item_shoppig_cart_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cart', ['shopping_cart_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('shoppig_cart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shoppig_cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_item_shoppig_cart_id_fkey', 'cart', ['shoppig_cart_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('shopping_cart_id')

    # ### end Alembic commands ###
