"""Order column cart  changed to cart_id

Revision ID: a32c06e79f74
Revises: 0fa65480a142
Create Date: 2024-04-28 12:15:41.517019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32c06e79f74'
down_revision = '0fa65480a142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('order_cart_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cart', ['cart_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('cart')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_cart_fkey', 'cart', ['cart'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###
