"""product_type price and name change to not unique

Revision ID: e0de7d53152f
Revises: 40c003e50fe5
Create Date: 2024-05-15 18:17:07.024874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0de7d53152f'
down_revision = '40c003e50fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.drop_constraint('product_type_name_key', type_='unique')
        batch_op.drop_constraint('product_type_price_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_type', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_type_price_key', ['price'])
        batch_op.create_unique_constraint('product_type_name_key', ['name'])

    # ### end Alembic commands ###
