"""stock_number not unique

Revision ID: f183cab9441f
Revises: e0de7d53152f
Create Date: 2024-05-15 19:09:56.540434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f183cab9441f'
down_revision = 'e0de7d53152f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.drop_constraint('product_item_stock_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_item', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_item_stock_number_key', ['stock_number'])

    # ### end Alembic commands ###
